version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: flowlite-neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/testTEST0
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_enabled=true
      - NEO4J_server_https_enabled=false

    volumes:
      - neo4j_data:/data
volumes:
  neo4j_data:
