version: "3.8"
services:
  neo4j:
    image: neo4j:5
    container_name: flowlite-neo4j
    ports:
      - "7474:7474"   # Browser
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH_FILE=/run/secrets/neo4j_auth
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_server_http_enabled=true
      - NEO4J_server_https_enabled=false

    volumes:
      - neo4j_data:/data

    secrets:
      - neo4j_auth

volumes:
  neo4j_data:

secrets:
  neo4j_auth:
    file: ./secrets/neo4j_auth.txt
